name: Infrastructure CI

on:
  push:
    branches:
      - develop
    paths:
      - 'Weather-dashboard-API/infra/**'
      - '.github/workflows/infra-ci.yml'
  pull_request:
    branches:
      - develop
    paths:
      - 'Weather-dashboard-API/infra/**'

jobs:
  validate-terraform:
    name: 'Validate Terraform'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v3 # Using latest version of the action
        with:
          terraform_version: 1.8.5 # Specify a valid, recent version of Terraform CLI

      - name: 'Terraform Init'
        run: terraform init
        working-directory: ./Weather-dashboard-API/infra/environments/dev

      - name: 'Terraform Format'
        run: terraform fmt -check
        working-directory: ./Weather-dashboard-API/infra

      - name: 'Terraform Validate'
        run: terraform validate
        working-directory: ./Weather-dashboard-API/infra/environments/dev

      - name: 'Run Checkov Security Scan'
        uses: bridgecrewio/checkov-action@v12 # Pinning to a specific major version
        with:
          directory: ./Weather-dashboard-API/infra/
          framework: terraform
          # Skipped security checks (intentional for this project):
          # CKV_AWS_130: Public subnets auto-assign public IPs (required for public subnets)
          # CKV_AWS_338: CloudWatch log retention < 1 year (7 days is sufficient for dev/testing)
          # CKV_AWS_158: [Add description of what this check does and why it's skipped]
          skip_check: CKV_AWS_130,CKV_AWS_338,CKV_AWS_158

      - name: Display Skipped Security Checks
        run: |
          echo "ℹ️  The following Checkov security checks were intentionally skipped:"
          echo "   • CKV_AWS_130: Public subnets auto-assign public IPs (required for public subnets)"
          echo "   • CKV_AWS_338: CloudWatch log retention < 1 year (7 days is sufficient for dev/testing)"
          echo "   • CKV_AWS_158: Additional security check (deferred for this iteration)"

      - name: Terraform Plan (Dev)
        id: plan-dev
        run: |
          cd Weather-dashboard-API/infra/environments/dev
          terraform plan -input=false -no-color
        continue-on-error: true
